tested code
icub-tech-iit/study-improve-head-edpr pull request #2
Opened 2021-06-23 13:30 UTC by davidetome

Added:

- README.md
- scr folder

2021-06-23 13:41 UTC, pattacini requested changes
Nicely done!
Only minor fixes you may integrate straight away.

2021-06-23 13:41 UTC, pattacini commented on log-joint/README.md
> +The snippet code allow to move a joint between two set points both in position and pwm control mode and logs following joint data:
```suggestion
The snippet code allows moving a joint between two set points both in position and PWM control mode and logs the following joint data:
```

2021-06-23 13:41 UTC, pattacini commented on log-joint/README.md
> +Is possible to run the code to control the joint both in `position` and `pwm` control mode by passing to it proper parameters via CLI.
```suggestion
It is possible to run the code to control the joint both in `position` and `PWM` control mode by passing to it proper parameters via CLI.
```

2021-06-23 13:44 UTC, pattacini approved these changes

2021-06-23 13:45 UTC, merged

2021-06-24 15:11 UTC, pattacini commented
Hi @arrenglover

With this PR, @davidetome made available a testing suite we aim to use for verifying the performance of the `iCubGenova02` current head as I told you early on.

The code is documented at https://github.com/icub-tech-iit/study-improve-head-edpr/tree/code/log-joint.

@davidetome will be off next week but back to work soon afterward to assist you with the preliminary tests.

2021-06-24 15:16 UTC, arrenglover commented
okay great! thanks @davidetome and @pattacini, that sounds good to me.